### ISSUE TITLE
Agent Phone status not getting updated

### ISSUE THREAD

**Issue by VasuInukollu** [xema-in/agent#1]
When the phone goes offine, this event is generated but not reflecting on the screen.

```json
{"event":"DeviceStateChanged","device":"1001","state":"UNAVAILABLE","timestamp":"2020-12-17T12:12:43.784+05:30","stateCode":1}
```

**Comment by KalluriM** [comment]
Now Agent Phone status is getting updated with below code changes

 case 'UNAVAILABLE':
          this.btnColor = 'btn-secondary';
          break;
